import type { Metadata } from "next";
import { Raleway } from 'next/font/google'
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const raleway = Raleway({
  subsets: ['latin'],
  // optional: specify weights
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  // optional: specify styles
  style: ['normal', 'italic'],
  variable: '--font-raleway', // This allows you to use it as a CSS variable
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased overflow-x-hidden`}>
        <Navbar />
        <div className="overflow-x-hidden mt-[-100px]">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}